language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then python -m pip install --upgrade 'pip<21.0' 'setuptools<45' wheel; fi
  - python setup.py install
before_script:
  - flake8 .
script:
  - python setup.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: always
